name: 'Dependencies'
on: [push, pull_request]
    
permissions:
  contents: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v4
        
